{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "bionic",
  "addons": {
    "apt": {
      "packages": [
        "python-pygments"
      ]
    }
  },
  "before_install": [
    "chmod +x binaries/hugo"
  ],
  "install": [
    "rm -rf public || exit 0"
  ],
  "script": [
    "binaries/hugo",
    "echo -e 'leons.dev' > public/CNAME"
  ],
  "deploy": [
    {
      "provider": "pages",
      "skip_cleanup": true,
      "local_dir": "public",
      "on": {
        "branch": [
          "master"
        ]
      },
      "token": "$GH_TOKEN"
    }
  ]
}
